### PR TITLE
Remove extraneous bounds check

### PR DESCRIPTION
**Pull request by carlbennett**

### CODE REVIEW

**Review by Davnit — CHANGES_REQUESTED** [review]
Thanks.

`g_Channel.Users(g_Channel.Users.Count)` is a valid user so the -1 in the loop will prevent the last user from being processed.

**Comment by carlbennett** [comment]
Really? So if there's 1 user then `Count` is zero?

**Comment by Davnit** [comment]
The collection starts at 1 and ends with `Count`.

**Comment by carlbennett** [comment]
Looked at the code in `trunk/clsChannelObj.bas` and figured it out. That's really odd. Fixed.

**Pull request merged**
